#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/wherewego;MODE=MySQL;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    url: jdbc:mysql://wwg-database.czxjlmbfh7qh.ap-northeast-2.rds.amazonaws.com:3306/wwg
    username: admin
    password: okcnd0087??
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true #시스템 아웃으로 출력
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: adcdm87@gmail.com
    password: eamktstumiwmymks
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug #로그를 통해서 출력
    org.hibernate.type: trace


jwt:
  header: Authorization
  secret: d3dnUHJvamVjdHd3Z1Byb2plY3R3d2dQcm9qZWN0d3dnUHJvamVjdHd3Z1Byb2plY3Q
  token-validity-in-seconds: 86400